[package]
name = "keyforge-sim"
version = "0.1.0"
authors = ["Quinn Romanek <quinnromanek@gmail.com>"]

[dependencies]
env_logger = "0.6.0"
log = "0.4.6"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0"
reqwest = "0.9.5"
rand = "0.6.1"
rlua = "0.15.3"
uuid = "0.7"

